# Generated by Django 3.1.2 on 2020-10-25 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('Address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Laundry', models.CharField(max_length=50)),
                ('Kitchen', models.CharField(max_length=50)),
                ('InternetTV', models.CharField(max_length=50)),
                ('CommonAreas', models.CharField(max_length=50)),
                ('AC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('Address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Bedrooms', models.IntegerField()),
                ('Bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Price', models.IntegerField()),
                ('Safety', models.IntegerField()),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Bedrooms', models.IntegerField(primary_key=True, serialize=False)),
                ('Bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Price', models.IntegerField()),
                ('Safety', models.IntegerField()),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.amenities')),
            ],
        ),
    ]
