# Generated by Django 3.1.2 on 2020-10-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='Furnished',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
