# Generated by Django 3.1.2 on 2020-10-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_amenities_furnished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='Furnished',
            field=models.BooleanField(),
        ),
    ]
