# Generated by Django 2.0.2 on 2020-10-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_dorms'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorms',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
