# Generated by Django 3.1.2 on 2020-10-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_dorms_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
