# Generated by Django 2.0.2 on 2020-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_auto_20201027_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorms',
            name='myfield',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red')], default='N/A', max_length=256),
        ),
    ]
