# Generated by Django 2.0.2 on 2020-10-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_dorms_myfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorms',
            name='myfield',
        ),
        migrations.RemoveField(
            model_name='house',
            name='Name',
        ),
        migrations.AlterField(
            model_name='amenities',
            name='AC',
            field=models.CharField(choices=[('None', 'None'), ('Central', 'Central'), ('Window', 'Window')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='CommonAreas',
            field=models.CharField(choices=[('None', 'None'), ('Few', 'Few'), ('Many', 'Many')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='InternetTV',
            field=models.CharField(choices=[('Included', 'Included'), ('Not Included', 'Not Included')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='Kitchen',
            field=models.CharField(choices=[('None', 'None'), ('Half', 'Half'), ('Full', 'Full')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='Laundry',
            field=models.CharField(choices=[('None', 'None'), ('Room', 'Room'), ('Building', 'Building')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='Safety',
            field=models.CharField(choices=[('Least Safe', 'Least Safe'), ('Less Safe', 'Less Safe'), ('More Safe', 'More Safe'), ('Most Safe', 'Most Safe')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='dorms',
            name='Bathrooms',
            field=models.CharField(choices=[('Private', 'Private'), ('Communal', 'Communal')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='dorms',
            name='Roomstyle',
            field=models.CharField(choices=[('Single', 'Single'), ('Shared Single', 'Shared Single'), ('Double', 'Double'), ('Triple', 'Triple')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='dorms',
            name='Safety',
            field=models.CharField(choices=[('Least Safe', 'Least Safe'), ('Less Safe', 'Less Safe'), ('More Safe', 'More Safe'), ('Most Safe', 'Most Safe')], default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='house',
            name='Safety',
            field=models.CharField(choices=[('Least Safe', 'Least Safe'), ('Less Safe', 'Less Safe'), ('More Safe', 'More Safe'), ('Most Safe', 'Most Safe')], default='N/A', max_length=50),
        ),
    ]
