# Generated by Django 2.0.2 on 2020-10-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_auto_20201027_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='InternetTV',
            field=models.CharField(choices=[('Not Included', 'NotIncluded'), ('Included', 'Included')], default='N/A', max_length=50),
        ),
    ]
